# Generated by Django 4.2.7 on 2024-01-02 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_product_image_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='created_at',
            new_name='added_at',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
