# Generated by Django 4.2.7 on 2024-01-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_electronicproductimage_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicproductimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
